@startuml
ConsentSystemA -> ConsentSystemB: Subscribe to receive consent events
loop 
   ConsentSystemB -> ConsentSystemA: Send consent event
end 
ConsentSystemA -> ConsentSystemB: End subscription to consent events
@enduml
