@startuml
ConsentSystem -> Consenter: Send the rendered consent form
loop
    Consenter -> Consenter: Reviews the consent form 
    Consenter -> ConsentSystem: Saves partially filled form
end
@enduml
