@startuml
Consenter -> ConsentSystem: Revoke Consent event is sent to system
ConsentSystem -> ConsentSystem: Invoked business process of revoking consent 
ConsentSystem -> ConsentSystem: Deactivate consent
@enduml